/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancounion;


import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Date;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JTextField;







/**
 *
 * @author holij
 */
public class RegistroVentas extends javax.swing.JFrame {
        private String nombreUsuario;

    


    /**
     * Creates new form BIBLIOTECA
     */
     
    public RegistroVentas() {
        
        initComponents();
        this.setTitle("Registro de ventas");
        this.setLocationRelativeTo(null);


  
    }
     private void limpiarCajas(){
        txtCodigoCredito.setText(null);
        cbxNombreCredito.setSelectedIndex(0);
        txtInteres.setText(null);
        txtNumCuentaCliente.setText(null);
        txtCreditoMonto.setText(null);
        txtRequisitosCredito1.setText(null);
        txtDescripcion.setText(null);
        DateFechaActivacion.setDate(null);
        DateFechaVencimiento.setDate(null);
       
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnVENTA = new javax.swing.JButton();
        DateFechaActivacion = new com.toedter.calendar.JDateChooser();
        txtCodigoCredito = new javax.swing.JTextField();
        txtCreditoMonto = new javax.swing.JTextField();
        txtInteres = new javax.swing.JTextField();
        btnVerVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DateFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumCuentaCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtRequisitosCredito1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBUSCAR = new javax.swing.JButton();
        txtBUSCAR = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        cbxNombreCredito = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log-out_1.png"))); // NOI18N
        jToggleButton1.setText("Cerrar Sesion");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnVENTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnVENTA.setText("Guardar Venta");
        btnVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVENTAActionPerformed(evt);
            }
        });

        txtCodigoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCreditoActionPerformed(evt);
            }
        });

        btnVerVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dollar-sign_2.png"))); // NOI18N
        btnVerVentas.setText("Mis Ventas");
        btnVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVentasActionPerformed(evt);
            }
        });

        jLabel1.setText("Credito Monto");

        jLabel3.setText("Codigo");

        jLabel4.setText("Nombre");

        jLabel5.setText("Interes");

        jLabel6.setText("Fecha Activacion");

        jLabel7.setText("Fecha Vencimiento");

        jLabel8.setText("Numero De Cuenta Cliente");

        jLabel9.setText("Requisitos");

        jLabel10.setText("Descripcion");

        btnBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recruitment (1).png"))); // NOI18N
        btnBUSCAR.setText("Buscar Codigo Venta");
        btnBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBUSCARActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh-ccw.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash-2.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        cbxNombreCredito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Pensionados", "Secretaria de educacion", "Fuerzas Armadas", "Activos" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtCodigoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(DateFechaActivacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtCreditoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtRequisitosCredito1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbxNombreCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(DateFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNumCuentaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtInteres))
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBUSCAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 99, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVENTA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBUSCAR)
                    .addComponent(txtBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DateFechaActivacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DateFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(cbxNombreCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreditoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCuentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRequisitosCredito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVENTA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerVentas)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MenuInicial entrada = new MenuInicial();
        entrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasActionPerformed
            VerVentas V = new VerVentas();
            V.setVisible(true);
            this.setVisible(false);

           }//GEN-LAST:event_btnVerVentasActionPerformed
private boolean verificarCampos() {
    JComponent[] campos = {txtCodigoCredito, cbxNombreCredito, txtCreditoMonto, txtRequisitosCredito1, txtDescripcion, txtInteres, txtNumCuentaCliente};
    String[] nombres = {"Código Crédito", "Nombre Crédito", "Monto", "Requisitos", "Descripción", "Interés", "Número de Cuenta Cliente"};

    for (int i = 0; i < campos.length; i++) {
        if (campos[i] instanceof JTextField && ((JTextField) campos[i]).getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo " + nombres[i] + " está vacío");
            return false;
        } else if (campos[i] instanceof JComboBox && ((JComboBox<?>) campos[i]).getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún valor en el campo " + nombres[i]);
            return false;
        } else if (campos[i] instanceof JComboBox && ((JComboBox<?>) campos[i]).getSelectedItem().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un valor válido en el campo " + nombres[i]);
            return false;
        }
    }

    // Todos los campos están llenos
    return true;
}

private void validarDatos(String codigoCredito, String nombreCredito, BigDecimal monto, String requisitos, String descripcion, BigDecimal interes, String numCuentaCliente) throws Exception {
    
    
    if (!codigoCredito.matches("\\d{1,11}")) {
        throw new Exception("El código de crédito debe ser un número entero de hasta 11 dígitos");
    }
    if (nombreCredito.length() > 45) {
        throw new Exception("El nombre del crédito no puede tener más de 45 caracteres");
    }
    if (monto.compareTo(new BigDecimal("999999999.99")) > 0) {
        throw new Exception("El monto no puede ser mayor a 999999999.99");
    }
    if (requisitos.length() > 100) {
        throw new Exception("Los requisitos no pueden tener más de 100 caracteres");
    }
    if (descripcion.length() > 80) {
        throw new Exception("La descripción no puede tener más de 80 caracteres");
    }
    if (interes.compareTo(new BigDecimal("0.99")) > 0) {
        throw new Exception("El interés no puede ser mayor a 0.99");
    }
     if (!numCuentaCliente.matches("\\d{12}")) {
        throw new Exception("El número de cuenta del cliente debe ser un número entero de 12 dígitos");
    }
}

    
  private boolean agregarVenta(String codigoCredito, String nombreCredito, String fechaActivacion, String fechaVencimiento, BigDecimal monto, String requisitos, String descripcion, BigDecimal interes, String numCuentaCliente, String codigoVendedor) {
    boolean resultado = false;

    conectar cc = new conectar();
    Connection cn = cc.conexion();

    try {
        PreparedStatement ps = cn.prepareStatement("INSERT INTO creditos (codigo, nombre, fecha_activacion, fecha_vencimiento, monto, requisitos, descripcion, interes, numero_cuenta_cliente, codigo_aliado) VALUES (?,?,?,?,?,?,?,?,?,?)");

        ps.setString(1, codigoCredito);
        ps.setString(2, nombreCredito);
        ps.setString(3, fechaActivacion);
        ps.setString(4, fechaVencimiento);
        ps.setBigDecimal(5, monto);
        ps.setString(6, requisitos);
        ps.setString(7, descripcion);
        ps.setBigDecimal(8, interes);
        ps.setString(9, numCuentaCliente);
        ps.setString(10, codigoVendedor);

        int referencia = ps.executeUpdate();

        if (referencia > 0) {
            resultado = true;
        }

    } catch (SQLException e) {
        System.err.println("Error al agregar venta: " + e);
    } finally {
        try {
            if (cn != null) {
                cn.close();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    return resultado;
}




    private void btnVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVENTAActionPerformed
           if (!verificarCampos()) {
        // Hay algún campo vacío o no válido, no se puede continuar
        return;
    }

    String codigoCredito = txtCodigoCredito.getText();
    String nombreCredito = cbxNombreCredito.getSelectedItem().toString();

    BigDecimal monto = new BigDecimal(txtCreditoMonto.getText());
    String requisitos = txtRequisitosCredito1.getText();
    String descripcion = txtDescripcion.getText();
    BigDecimal interes = new BigDecimal(txtInteres.getText());
    String numCuentaCliente = txtNumCuentaCliente.getText();
    String codigoVendedor = IniciarSesion.codigoVendedor;

    // Validar los datos antes de guardarlos en la base de datos
    try {
        validarDatos(codigoCredito, nombreCredito, monto, requisitos, descripcion, interes, numCuentaCliente);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        return;
    }

    java.util.Date fechaActivacion = DateFechaActivacion.getDate();
    java.util.Date fechaVencimiento = DateFechaVencimiento.getDate();

    // Convertir las fechas a cadenas de texto en el formato deseado
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaActivacionTexto = sdf.format(fechaActivacion);
    String fechaVencimientoTexto = sdf.format(fechaVencimiento);

    boolean resultado = agregarVenta(codigoCredito, nombreCredito, fechaActivacionTexto, fechaVencimientoTexto, monto, requisitos, descripcion, interes, numCuentaCliente, codigoVendedor);

    if (resultado) {
        JOptionPane.showMessageDialog(this, "Venta Agregada");
        limpiarCajas();
    } else {
        JOptionPane.showMessageDialog(this, "Error al agregar Venta");
        limpiarCajas();
    }
    }//GEN-LAST:event_btnVENTAActionPerformed

    private void txtCodigoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCreditoActionPerformed

    private void btnBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBUSCARActionPerformed
 JOptionPane.showMessageDialog(null, "Por cuestiones de seguridad si desea modificar información del cliente, solo podrá modificar estos campos -Nombre Crédito, Requisitos, Descripción y número de cuenta del cliente-");
    
    conectar cc = new conectar();
    java.sql.Connection cn = cc.conexion();
    ResultSet rs = null;

    try {
        PreparedStatement pst = cn.prepareStatement("SELECT * FROM creditos WHERE codigo = ? AND codigo_aliado = ?");
        pst.setString(1, txtBUSCAR.getText());
        pst.setString(2, IniciarSesion.codigoVendedor);

        rs = pst.executeQuery();

        if (rs.next()) {
            txtCodigoCredito.setText(rs.getString("codigo"));
            txtInteres.setText(rs.getString("interes"));
            cbxNombreCredito.setSelectedItem(rs.getString("nombre"));
            txtNumCuentaCliente.setText(rs.getString("numero_cuenta_cliente"));
            txtCreditoMonto.setText(rs.getString("monto"));
            txtRequisitosCredito1.setText(rs.getString("requisitos"));
            txtDescripcion.setText(rs.getString("descripcion"));

            // Obtener las fechas como cadenas de texto
            String fechaActivacionStr = rs.getString("fecha_activacion");
            String fechaVencimientoStr = rs.getString("fecha_vencimiento");

            // Convertir las cadenas de texto a objetos java.util.Date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                java.util.Date fechaActivacion = dateFormat.parse(fechaActivacionStr);
                java.util.Date fechaVencimiento = dateFormat.parse(fechaVencimientoStr);

                // Establecer las fechas en los componentes correspondientes
                DateFechaActivacion.setDate(fechaActivacion);
                DateFechaVencimiento.setDate(fechaVencimiento);
            } catch (ParseException ex) {
                System.err.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No existe una Venta con ese código");
            limpiarCajas();
        }
    } catch (HeadlessException e) {
        System.err.println(e);
    } catch (SQLException ex) {
        Logger.getLogger(RegistroVentas.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            if (cn != null) {
                cn.close();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    }//GEN-LAST:event_btnBUSCARActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        
       conectar cc = new conectar();
    Connection cn = cc.conexion();
    try {
        PreparedStatement ps = createUpdateStatement(cn);
        setUpdateStatementParameters(ps);

        int a = ps.executeUpdate();
        if (a > 0) {
            JOptionPane.showMessageDialog(this, "Venta Modificada");
            limpiarCajas();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar Venta");
            limpiarCajas();
        }
    } catch (SQLException | HeadlessException e) {
        System.err.println("Error Nota: Todos los datos que no fueron guardados se eliminaran al cerrar el sistema" + e);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed
private PreparedStatement createUpdateStatement(Connection cn) throws SQLException {
    String sql = "UPDATE creditos SET nombre=?, requisitos=?, descripcion=?, numero_cuenta_cliente=? WHERE codigo=? AND codigo_aliado=?";
    return cn.prepareStatement(sql);
}

private void setUpdateStatementParameters(PreparedStatement ps) throws SQLException {
    ps.setString(1, (String) cbxNombreCredito.getSelectedItem());
    ps.setString(2, txtRequisitosCredito1.getText());
    ps.setString(3, txtDescripcion.getText());
    ps.setString(4, txtNumCuentaCliente.getText());
    ps.setString(5, txtCodigoCredito.getText());
    ps.setString(6, IniciarSesion.codigoVendedor);
}
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
           conectar cc = new conectar();
    Connection cn = cc.conexion();
    try {
        if (confirmDelete()) {
            PreparedStatement pst = createDeleteStatement(cn);
            setDeleteStatementParameters(pst);

            int res = pst.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Venta Eliminada");
                limpiarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar Venta");
                limpiarCajas();
            }
        }
    } catch (HeadlessException | NumberFormatException | SQLException e) {
        System.err.println(e);
    }
    
    }//GEN-LAST:event_btnEliminarActionPerformed
private boolean confirmDelete() {
    String message = "Si elige si no podra recuperar los datos borrados";
    String title = "¿Esta seguro que dese eliminar la venta?";
    int option = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
    return option == JOptionPane.YES_OPTION;
}

private PreparedStatement createDeleteStatement(Connection cn) throws SQLException{
    String sql = "DELETE FROM creditos WHERE codigo=?";
    return cn.prepareStatement(sql);
}

private void setDeleteStatementParameters(PreparedStatement pst) throws SQLException {
    pst.setString(1, txtBUSCAR.getText());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateFechaActivacion;
    private com.toedter.calendar.JDateChooser DateFechaVencimiento;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBUSCAR;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVENTA;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JComboBox<String> cbxNombreCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtBUSCAR;
    private javax.swing.JTextField txtCodigoCredito;
    private javax.swing.JTextField txtCreditoMonto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtNumCuentaCliente;
    private javax.swing.JTextField txtRequisitosCredito1;
    // End of variables declaration//GEN-END:variables
}
